[[redirects]]
  from = "/interview"
  to = "/Interview.jsx"
  status = 200

[[redirects]]
  from = "/feedback"
  to = "Piechart"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
